
package com.actonate.carrier_label_service.utils.helpers.bluedart.org.tempuri;

import com.actonate.carrier_label_service.utils.helpers.bluedart.org.datacontract.schemas._2004._07.sapi_entities.*;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;



/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.0
 * 
 */
@WebService(name = "IWayBillGeneration", targetNamespace = "http://tempuri.org/")
public interface IWayBillGeneration {


    /**
     * 
     * @param request
     * @param profile
     * @return
     *     returns org.datacontract.schemas._2004._07.sapi_entities.WayBillGenerationResponse
     */
    @WebMethod(operationName = "GenerateWayBill", action = "http://tempuri.org/IWayBillGeneration/GenerateWayBill")
    @WebResult(name = "GenerateWayBillResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GenerateWayBill", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GenerateWayBill")
    @ResponseWrapper(localName = "GenerateWayBillResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GenerateWayBillResponse")
    public WayBillGenerationResponse generateWayBill(
        @WebParam(name = "Request", targetNamespace = "http://tempuri.org/")
                WayBillGenerationRequest request,
        @WebParam(name = "Profile", targetNamespace = "http://tempuri.org/")
                UserProfile profile);

    /**
     * 
     * @param request
     * @param profile
     * @return
     *     returns org.datacontract.schemas._2004._07.sapi_entities.ArrayOfWayBillGenerationResponse
     */
    @WebMethod(operationName = "ImportData", action = "http://tempuri.org/IWayBillGeneration/ImportData")
    @WebResult(name = "ImportDataResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ImportData", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ImportData")
    @ResponseWrapper(localName = "ImportDataResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ImportDataResponse")
    public ArrayOfWayBillGenerationResponse importData(
        @WebParam(name = "Request", targetNamespace = "http://tempuri.org/")
                ArrayOfWayBillGenerationRequest request,
        @WebParam(name = "Profile", targetNamespace = "http://tempuri.org/")
        UserProfile profile);

}
