
package com.actonate.carrier_label_service.utils.helpers.bluedart.org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.*;
import javax.xml.namespace.QName;
import javax.xml.ws.*;
import javax.xml.ws.handler.MessageContext;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "WayBillGeneration", targetNamespace = "http://tempuri.org/", wsdlLocation = "https://netconnect.bluedart.com/Ver1.10/Demo/ShippingAPI/WayBill/WayBillGeneration.svc?wsdl")
public class WayBillGeneration
    extends Service
{

    private final static URL WAYBILLGENERATION_WSDL_LOCATION;
    private final static WebServiceException WAYBILLGENERATION_EXCEPTION;
    private final static QName WAYBILLGENERATION_QNAME = new QName("http://tempuri.org/", "WayBillGeneration");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://netconnect.bluedart.com/Ver1.10/Demo/ShippingAPI/WayBill/WayBillGeneration.svc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WAYBILLGENERATION_WSDL_LOCATION = url;
        WAYBILLGENERATION_EXCEPTION = e;
    }

    public WayBillGeneration() {
        super(__getWsdlLocation(), WAYBILLGENERATION_QNAME);
    }

    public WayBillGeneration(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns IWayBillGeneration
     */
    @WebEndpoint(name = "WSHttpBinding_IWayBillGeneration")
    public IWayBillGeneration getWSHttpBindingIWayBillGeneration() {

        QName qname = new QName("http://tempuri.org/", "WSHttpBinding_IWayBillGeneration");

        IWayBillGeneration port = super.getPort(qname, IWayBillGeneration.class, new javax.xml.ws.soap.AddressingFeature());

//        Map<String, List<String>> requestHeaders = new HashMap<>();
//        List<String> headerArray = new ArrayList<>();
//        headerArray.add("http://www.w3.org/2005/08/addressing");
//        headerArray.add("Action");
//        headerArray.add("http://tempuri.org/IWayBillGeneration/GenerateWayBill");
//        headerArray.add("true");
//        requestHeaders.put("Action", headerArray);
//
//        BindingProvider bindingProvider = (BindingProvider)port;
//        bindingProvider.getRequestContext().put(MessageContext.HTTP_REQUEST_HEADERS, requestHeaders);

        return port;
    }

    private static URL __getWsdlLocation() {
        if (WAYBILLGENERATION_EXCEPTION!= null) {
            throw WAYBILLGENERATION_EXCEPTION;
        }
        return WAYBILLGENERATION_WSDL_LOCATION;
    }

}
